### ISSUE TITLE
抱歉，我知道不应该在该项目下提问。是关于 openwrt-ssr 的问题

### ISSUE THREAD

**Issue by laincat** [WouldChar/openwrt-udp2raw-speeder#1]
```
那边没有可以发 issues....只好发到这里了，抱歉
```

> 我是直接在 OpenWRT 最新开发源码上 编译（也许源码也会带来下面的问题，我等等会进行清空，重新编译试试，并清空路由上的所有数据测试）

是这样的，想使用 https://github.com/AlexZhuo/openwrt-dnsforwarder 该项目替代 pdnsd 使用，但是在设置和使用遇到问题了。（工作不正常，按道理应该是可行的说啊。烦恼，可以帮忙看看吗？）

> openwrt-dnsforwarder 如项目下的设置，然后把 127.0.0.1:53 填入 "DNS服务器地址和端口" 并选择 “使用其它 dns 转发”

想替换的原因：
* 您的 openwrt-ssr 这两天更新了代码，也遇到奇怪问题（在更新前是正常运作的）。
* pdnsd 已经停更很久了，也许很稳定吧。
* 想试试其它的方案

而问题 1 出现的状况如下：
* 表现为 openwrt-ssr 界面下，“DNS解析方式“的 pdnsd 显示没有安装，然而我是有安装的。
（安装但是没有进行任何设置。看代码是会通过脚本让其运作对吗？并不需要我去干预）
> 需要去打开 etc/config/pdnsd, 的 config pdnsd option enabled '1' 吗？

* 我也尝试直接用 SSR-DNS 也无法使用。

> 如需其它信息我会尽快提交。。。

**Comment by laincat** [comment]
```
shadowsocksr.config 该文件这一行是不是错的啊？运行直接出错了。
```
> option run_mode = 'router'

**Comment by fuqiang03** [comment]
pdnsd不需要干预，但有的版本pdnsd会开机自动运行。但是我的pdnsd界面能看到运行状态
